---
version: '3.7'

services:

  elasticsearch_ecommerce_search_sample:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch_ecommerce_search_sample
    volumes:
      # This volume will use the default path defined in Docker's setting to store all the container data.
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: elasticsearch_ecommerce_01
      cluster.name: ecommerce_sample_cluster
      network.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      # cluster.initial_master_nodes: elasticsearch_ecommerce_01
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - stack

  kibana_ecommerce_search_sample:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana_ecommerce_search_sample
    environment:
      server.name: kibana
      server.host: 0
      elasticsearch.hosts: http://elasticsearch_ecommerce_search_sample:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch_ecommerce_search_sample:9200
    ports:
      - "5601:5601"
    networks:
      - stack
    depends_on:
      - elasticsearch_ecommerce_search_sample

# use docker volume to persist ES data outside of a container.
volumes:
  es_data:
    driver: local

networks:
  stack:
    driver: bridge
    name: stack
